name: deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: auth
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GCP_ACCOUNT }}"

            - name: install
              run: npm ci

            - name: build
              run: npm run build

            - name: upload
              uses: "google-github-actions/upload-cloud-storage@v1"
              with:
                  path: "dist"
                  destination: ${{ secrets.GCP_BUCKET }}
                  parent: false
                  process_gcloudignore: false
